// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvv40TwlLYBEbJ2-Tkqjsar9sgojQ5YpM',
    appId: '1:825162007364:web:ba8f5dd8bc6c4fb7640d11',
    messagingSenderId: '825162007364',
    projectId: 'elmovie-b11df',
    authDomain: 'elmovie-b11df.firebaseapp.com',
    storageBucket: 'elmovie-b11df.appspot.com',
    measurementId: 'G-16MKX9MSDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQR4WbpvkV2Y8CWVWl4I3ohbJN4ONfLw',
    appId: '1:825162007364:android:4073d2458bd156f7640d11',
    messagingSenderId: '825162007364',
    projectId: 'elmovie-b11df',
    storageBucket: 'elmovie-b11df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwsY23kuCUw_-v44f8-EzH4I55STjIeP4',
    appId: '1:825162007364:ios:c3f5bb2d1b9bc22d640d11',
    messagingSenderId: '825162007364',
    projectId: 'elmovie-b11df',
    storageBucket: 'elmovie-b11df.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
